name: it-is-my-first-workflow

on: [push, workflow_dispatch]
 

jobs:
  it-is-the-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print whatever I have given you
        run: |
          echo "I am a testing workflow"
          echo "My name is Alam Zia"

  it-is-the-second-job:
    needs: it-is-the-first-job
    runs-on: ubuntu-latest
    steps:
      - name: Print the second thing that I gave you
        run: echo "Hey, it is the parallel job in GitHub Actions"
