name: it is my first-workflow

on:
  workflow_dispatch

jobs:
  it-is-the-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print whatever ihave given you
        run: |
            echo "i am a testing workflow"
            echo " my name is alam zia"
